# Generated by Django 2.2.9 on 2020-02-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_searchdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchDetails',
        ),
    ]
