# Generated by Django 2.2.9 on 2020-02-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_delete_searchdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='For_Sale',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
