# Generated by Django 2.2.9 on 2020-02-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20200208_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='AFFINITY_PURIFIED_RABBIT_1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='AFFINITY_PURIFIED_RABBIT_1_LOT_No',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='AFFINITY_PURIFIED_RABBIT_2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='AFFINITY_PURIFIED_RABBIT_2_LOT_No',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='AFFNTY_PURFN_RABBT_1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='AFFNTY_PURFN_RABBT_2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='ALL_PRDCT_LOT_No_2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='ANTBDY_PROTN_A_RABBT_1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='ANTBDY_PROTN_A_RABBT_1_LOT_No',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='ANTBDY_PROTN_A_RABBT_2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='Accession_No',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='CNJGTS_BIOTIN_LOCTN',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='CNJGTS_BIOTIN_LOCTN_FITC_Biotin',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='CNJGTS_FITC_RABBIT_No',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='CNJGTS_FITC_SMPL_PACK',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='CNJGTS_FITC_TUBES_DATE',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='CNJGTS_FITC_TUBES_LOCTN_1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='CNJGTS_FITC_TUBES_LOCTN_2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='COLMN_DATE',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='COLMN_LOCTN_BOX_No',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='COLMN_NAME',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='COMNT_n_LotNo',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='CR_Experimental',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='CR_Theoritical',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='Category',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='Column49',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='ESP_NOTES',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='EXTD_Rabbit_1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='EXTD_Rabbit_2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='FREEZER_BOX',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='Final_Catalog',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='Host',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='LOT_No',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='MW',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='NOT_in_Location',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='No_Bottle_Rb1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='No_Bottle_Rb2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='No_Tubes',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='ORIGIN',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='Old_Catalog',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='PRDTS_3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='PRODUCT_LOCATION_2015_18_INVTRY',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='PRODUCT_LOCATION_BOX',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='PRODUCT_LOCATION_FRZR',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='PRODUCT_LOCATION_SMPLR_PACK',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='PURFN_PROTN_A_RABT_1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='PURFN_PROTN_A_RABT_2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='Peptide',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='Peptide_Lot_No',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='Peptide_Position',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='Peptide_Sequence',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='Peptide_Used',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='REMARKS',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='Rabbit_1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='Rabbit_2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='Retrnd_Conj_F_No',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='SPCL_Notes',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='SRM_BOX_No',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='SRM_FRZR_No',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='SRM_Rb_1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='Synonym',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='TB_BOX_No',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='TB_FRZR_No',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='Target_Name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='WB_CONTRL_LOCTN_BOX_FRZR',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='WB_CONTRL_TUBES_No',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
