# Generated by Django 2.2.9 on 2020-03-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_search_srm_rb_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='ANTBDY_PROTN_A_RABBT_2_LOT_No',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
